### ISSUE TITLE
Missing files for visualization gallery task

### ISSUE THREAD

**Issue by nhintruong** [tdhock/sandia-enrollment#1]
Hi @tdhock As mentioned my previous PR, I was trying to port the figure in [Analysis of enrollment data for resistive memory devices](https://github.com/tdhock/sandia-enrollment/blob/master/Updated-R46Sandia-cv-figure.R) source code when it required the file "Updated-R46Sandia-cv.xlsx". I found the link for this file (https://github.com/tdhock/sandia-enrollment/blob/master/Updated-R46Sandia.xlsx) but it seems to be no longer working. Could you please recheck this file for me? Thank you very much for your guidance

**Comment by tdhock** [comment]
I don't think these data were ever public, so please add this to the list of data viz which can not be ported

**Comment by nhintruong** [comment]
Here is the issue (https://github.com/animint/gallery/issues/7) for the non-portable visualizations. Thank you for your comment.
